apiVersion: skaffold/v2alpha3
kind: Config
metadata:
  name: blog
deploy:
  kubectl:
    manifests:
    - ./infra/k8s/**
build:
  local:
    push: false
  artifacts:
    - image: pjgeutjens/blog_client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
       manual:
       - src: "src/**/*.js"
         dest: .
    - image: pjgeutjens/blog_comments
      context: comments
      docker:
        dockerfile: Dockerfile
      sync:
       manual:
       - src: "*.js"
         dest: .
    - image: pjgeutjens/blog_event_bus
      context: event-bus
      docker:
        dockerfile: Dockerfile
      sync:
       manual:
       - src: "*.js"
         dest: .
    - image: pjgeutjens/blog_moderation
      context: moderation
      docker:
        dockerfile: Dockerfile
      sync:
       manual:
       - src: "*.js"
         dest: .
    - image: pjgeutjens/blog_posts
      context: posts
      docker:
        dockerfile: Dockerfile
      sync:
       manual:
       - src: "*.js"
         dest: .
    - image: pjgeutjens/blog_query
      context: query
      docker:
        dockerfile: Dockerfile
      sync:
       manual:
       - src: "*.js"
         dest: .
  
